"""init db

Revision ID: 6e5fae70d9b2
Revises: 
Create Date: 2024-12-14 23:46:32.326212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5fae70d9b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ddos',
    sa.Column('saddr', sa.String(), nullable=False),
    sa.Column('avgDur', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('saddr')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ddos')
    # ### end Alembic commands ###
